### PR TITLE
Add faraday retry middleware

### PR DESCRIPTION
**Pull request by salekseev**

### CODE REVIEW

**Comment by joshk0** [comment]
This is something I really want -- what's blocking this from being merged?

**Comment by salekseev** [comment]
> This is something I really want -- what's blocking this from being merged?

Unfortunately it seems that this project is defunct.

**Comment by RootTJNII** [comment]
How do you enable this middleware in the context of Oktakit?  I tried

```
Oktakit::Client::MIDDLEWARE.request(:retry, :max => 2, :interval => 1.0, :interval_randomness => 0.5, :backoff_factor => 2, :exceptions => [Oktakit::RateLimitError, Timeout::Error])
```

But it still appears to fail on the first Oktakit::RateLimitError.

**Comment by salekseev** [comment]
> How do you enable this middleware in the context of Oktakit? I tried
> 
> ```
> Oktakit::Client::MIDDLEWARE.request(:retry, :max => 2, :interval => 1.0, :interval_randomness => 0.5, :backoff_factor => 2, :exceptions => [Oktakit::RateLimitError, Timeout::Error])
> ```
> 
> But it still appears to fail on the first Oktakit::RateLimitError.

Something along those lines:

```
stack = Faraday::RackBuilder.new do |builder|
  builder.use Faraday::Request::Retry, exceptions: [Oktakit::RateLimitError, Timeout::Error]
  builder.use Oktakit::Response::RaiseError
  builder.adapter Faraday.default_adapter
end
Oktakit::Client::MIDDLEWARE = stack

client = Oktakit::Client.new(token: 't0k3n', api_endpoint: 'https://my-great-org.oktapreview.com/api/v1')
```

should work...

**Comment by salekseev** [comment]
> How do you enable this middleware in the context of Oktakit? I tried
> 
> ```
> Oktakit::Client::MIDDLEWARE.request(:retry, :max => 2, :interval => 1.0, :interval_randomness => 0.5, :backoff_factor => 2, :exceptions => [Oktakit::RateLimitError, Timeout::Error])
> ```
> 
> But it still appears to fail on the first Oktakit::RateLimitError.

Something along the lines of:

```
stack = Faraday::RackBuilder.new do |builder|
  builder.use Faraday::Request::Retry, exceptions: [Timeout::Error]
  builder.use Oktakit::Response::RaiseError
  builder.adapter Faraday.default_adapter
end
Oktakit::Client::MIDDLEWARE = stack

client = Oktakit::Client.new(token: 't0k3n', api_endpoint: 'https://my-great-org.oktapreview.com/api/v1')
```

should work. Your snippet specifically disables retries for `Oktakit::RateLimitError`.

**Comment by RootTJNII** [comment]
> Your snippet specifically disables retries for Oktakit::RateLimitError

Oh, derp, I misread the docs.  Thanks, I'll give that a shot 👍

**Comment by jonpulsifer** [comment]
Hey @salekseev, sorry for being defunct 😄 , if you're still interested in this PR please rebase off current master and I'll try to get it in. (rubocop is fixed)

Thanks

**Review by jonpulsifer — APPROVED** [review]

**Comment by tomekchime** [comment]
Curious if there are any plans to merge this in?

**Comment by ltk** [comment]
Unfortunately faraday-related updates are a little challenging to safely merge right now because of how loosely constrained our faraday dependency is at the moment. (e.g. Faraday 2.x doesn't actually define `Faraday::Request::Retry` anymore; it's in a separate gem now.) It's manageable, somebody just needs to take the time to manage it. :-)

Additionally for this PR, I think it's a little heavy-handed to enable retry behavior by default. I'd prefer to make behavior more easily configurable. Curious about others' thoughts on this.

**Pull request closed without merging**
