### PR TITLE
Expose error data

### PR DESCRIPTION
**Pull request by RootTJNII**
This PR makes the data method on the Error class public so that the Okta error code can be read.

```
[3] pry(main)> begin
[3] pry(main)*   client.get_user("baduser")
[3] pry(main)* rescue => exc
[3] pry(main)*   puts exc.data
[3] pry(main)* end
{:errorCode=>"E0000007", :errorSummary=>"Not found: Resource not found: baduser (User)", :errorLink=>"E0000007", :errorId=>"oaem_M8Zz4nRwKAwZa88nWrEA", :errorCauses=>[]}
```

https://developer.okta.com/docs/reference/error-codes/#example-errors-listed-by-error-code

### CODE REVIEW

**Comment by delian7** [comment]
@RootTJNII i'm curious as to what happened with this PR. I am using the OKTA kit gem and would love to have these errors appear.

**Comment by jonpulsifer** [comment]
@RootTJNII can you rebase and remove the rubocop commit? I made some changes in https://github.com/Shopify/oktakit/pull/33 (and merged your other PR finally)

**Comment by TJNII** [comment]
@thatguysimon I opened this a couple years ago from a work account I no longer have access to.  I think we should close this PR because @jonpulsifer has requested the Rubocop commit be removed, and I no longer have access to the source branch.  If you need this I recommend opening a new PR with just commit aba4025.

**Comment by ltk** [comment]
Closing in favor of 593089f3bbfc8c5f0be231edcf55d2520424d8a2

**Pull request closed without merging**
